# Generated by Django 5.1.1 on 2024-09-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_remove_book_cover_image_remove_book_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="book_covers/"),
        ),
        migrations.AlterField(
            model_name="book",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
